# -*- mode: ruby -*-
# vi: set ft=ruby :
$provision_pve6 = <<-SCRIPT
# Set noninteractive apt frontend
export DEBIAN_FRONTEND=noninteractive

# Update system
apt update
apt -y full-upgrade
apt -y install vim expect

# Set root passwd
echo "root:vagrant"|chpasswd

# Prepare hosts file
IP=$(ip route get 8.8.4.4 | head -1 | awk '{print $7}')
sed "s/127.0.1.1/${IP}/g" /etc/resolv.conf
eval $(echo "sed -i 's/127.0.1.1/${IP}/g' /etc/hosts")

# Install pve6
echo "deb http://download.proxmox.com/debian/pve buster pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
wget http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg -O /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
apt update
apt -y full-upgrade
apt install -y proxmox-ve postfix open-iscsi
apt remove -y os-prober
eval $(echo "sed -i 's/${IP}/127.0.1.1/g' /etc/hosts")

# Prepare vm to build vagrant box
apt-get clean
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY
cat /dev/null > ~/.bash_history
history -c
SCRIPT

Vagrant.configure("2") do |config|
    # Provision base box
    config.vm.define :"pve6" do |config|
        config.vm.synced_folder ".", "/vagrant", disabled: true
        config.vm.box = "debian/buster64"
        config.vm.box_version = "10.0.0"
        config.vm.box_check_update = false
        config.vm.network "forwarded_port", guest: 8006, host: 8006
        config.vm.hostname = "pve6"

        config.vm.provider 'virtualbox' do |v|
            v.customize ['modifyvm', :id, '--name', "pve6"]
            v.customize ['modifyvm', :id, '--cpus', 2]
            v.customize ['modifyvm', :id, '--memory', 512]
            v.customize ['modifyvm', :id, '--ioapic', 'on']
            v.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
            v.customize ['modifyvm', :id, '--nictype1', 'virtio']
        end
        config.vm.provision "shell", run: "once", inline: $provision_pve6
    end
end
